<?php
/**
 * Copyright (c) 2017.  hangzhou BOYE .Co.Ltd. All rights reserved
 */

/**
 * Created by PhpStorm.
 * User: 1
 * Date: 2017-02-11
 * Time: 09:37
 */

namespace app\src\bjpay\po;


class BjQueryBalanceReqPo extends BjNormalReqPo
{

    public function __construct()
    {
        parent::__construct();
        $this->setOpName('CebankQueryAvailableBalanceOp');
    }

    private $accountNo;

    /**
     * @return mixed
     */
    public function getAccountNo()
    {
        return $this->accountNo;
    }

    /**
     * @param mixed $accountNo
     */
    public function setAccountNo($accountNo)
    {
        $this->accountNo = $accountNo;
    }

    public function toXML()
    {
        $this->addParam("accountNo",$this->accountNo);
        return parent::toXML(); // TODO: Change the autogenerated stub
    }
}